services:
  app:
    build:
      context: .
#    ports:
#      - "8888:5000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    restart: on-failure
    command: >
      sh -c "npm run start:dev"

  db:
    image: mongo
#    ports:
#      - "5555:27017"
    env_file:
      - .env
    volumes:
      - ./mongo_db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf